---
name: main_branch
on:
  push:
    branches:
    - main
jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - name: check out code
      uses: actions/checkout@v7
    - name: log in to the registry
      uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: image build push
      run: make image-build-push
