---
name: publish (main)
on:
  push:
    branches:
    - main
jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - name: check out code
      uses: actions/checkout@v6
    - name: install cosign
      uses: sigstore/cosign-installer@v4.1.2
    - name: log in to the registry
      uses: docker/login-action@9f4a8ea54ed9055d5f86c993e1f2ffa674f98344
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build image and push
      run: make image-build-push
    - name: sign image
      run: make image-sign
